version: 1.0.{build}
before_build:
  - appveyor DownloadFile https://raw.githubusercontent.com/appveyor/ci/master/scripts/nuget-restore.cmd
  - nuget-restore
build:
  verbosity: minimal
test:
  # assemblies to test - optional
  assemblies:
    - '**\*.Test.dll'
